### ISSUE TITLE
Play RDS/RDS2/TVAsport

### ISSUE THREAD

**Issue by Evilmnkey** [Sphinxroot/IPTVM3U#9]
Hi,
    I have been having issues trying to add these links to Tivimate. Do these only work in Kodi? with a special plugin?

**Comment by Sphinxroot** [comment]
hello 

yes those list are mostly built for kodi as its using multiple plugin in it (Hybrid List) , and many  link  need the referer  or user agent to work properly . u can use kodi 18.9  whit the  pvr iptv simple client  (EPG Not ready yet )   Playlistloader addon  or see ma tele direct  addon that handle most of the list here  it whit the auto update when i add or change link in m3u list

if you use kodi  matrix  some link wont work because : some plugin that are not ported to 19+ yet

hope it help you :)

**Comment by mikhoul** [comment]
> and many link need the referer or user agent to work properly .

@Sphinxroot  Just to let you know I've made a request to the author of IPTVnator  (Linux/Win/Mac IPTV player with EPG) to add referer and UA support and it was added yesterday via: https://github.com/4gray/iptvnator/commit/a55f741a320db430987352289fd7847e050dcafd

So the next release will support REF + UA 😆 .

Regards :octocat:
